# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://basementcz.github.io
# baseurl: "http://rulearn.com"
baseurl: /russiantogo
title: Rulearn
email: tatiana.rulearn@gmail.com
author: Rulearn
description: > 
  'Rulearn'
copyright: 'Copyright &copy; 2017 All Rights Reserved.'
credits: 'Rulearn'
phone: +420 776 586 451

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/RussianToGo/?fref=ts

# constants
personalLessons: Individuální výuka ruštiny
groupLessons: Skupinová výuka
translations: Překlady a Korektura
conversations: Ruský konverzační klub
corpLessons: Firemní výuka ruštiny
skypeLessons: Výuka ruštiny přes Skype     
feedback: Reference 
contacts: Kontakt        