# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://basementcz.github.io
baseurl: /russiantogo
title: Russian To Go/Chcete mluvit rusky?
email: your-email@domain.com
author: russiantogo
description: > 
  'Russian To Go/Chcete mluvit rusky?'
copyright: 'Copyright &copy; 2017 All Rights Reserved.'
credits: 'Russian To Go/Chcete mluvit rusky?
'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/RussianToGo/?fref=ts
