# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://basementcz.github.io
baseurl: /russiantogo
title: Rulearn
email: tatiana.rulearn@gmail.com
author: Rulearn
description: > 
  'Rulearn'
copyright: 'Copyright &copy; 2017 All Rights Reserved.'
credits: 'Rulearn'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/RussianToGo/?fref=ts
